server:
  port: 8081

spring:
  application:
    name: multi-model-project
  ai:
    chat:
      client:
        enabled: false

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL}
          temperature: 0.2

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: codellama:latest
          temperature: 0.7

